### ISSUE TITLE
[Bug] Console is being spammed with error

### ISSUE THREAD

**Issue by JamesTalon** [DeathTech154/VoteRewards#12]
Getting these in my console, accompanied by some hefty lag on the server.

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at RewardsMod.RewardsModC.TryReadAllLines(String PathA, String PathB, Int32 ArraySize)
   at RewardsMod.RewardsModC.ReadPlayerData(String Username)
   at RewardsMod.APIHandler.OnTick(Object source, ElapsedEventArgs e)
-Error Occured in Tick Function-
```

**Comment by DeathTech154** [comment]
A while ago eco was messing with the shop issues and kept swapping between "" and ''.
This was not fixed because the devs were to fix it.

If this is still persisting let me know.

**Comment by DeathTech154** [comment]
Devs should have fixed this by now and no further interaction was observed.
