### ISSUE TITLE
Could not find file \Users\.txt

### ISSUE THREAD

**Issue by JamesTalon** [DeathTech154/VoteRewards#7]
Had this come up in the console after running /vrvotecheck 1 in game and buying skill points. Worked fine when previously attempting to use.

`Running Vote Tick function
System.IO.FileNotFoundException: Could not find file 'C:\Users\James\Desktop\ecoserver\Storage\ModData\RewardsMod\Users\.txt'.
File name: 'C:\Users\James\Desktop\ecoserver\Storage\ModData\RewardsMod\Users\.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at RewardsMod.RewardsModC.ReadPlayerData(String Username)
   at RewardsMod.APIHandler.OnTick(Object source, ElapsedEventArgs e)
-Error Occured in Tick Function-`

Edit: Possibly unrelated, but I noticed this in the servers startup
`ecoserver\Storage\ModData/RewardsMod\Users`

Shouldn't it be 
`ecoserver\Storage\ModData\RewardsMod\Users`? The difference being the \ between ModData and RewardsMod.

I was also able to fix the problem by copying over the fresh files for the Storage folder, but a restart didn't fix it originally.

**Comment by DeathTech154** [comment]
Yes, this is the error the server ticker gives when the List.txt gets corrupted. The way to make the error suppressed is to open the List.txt file and remove any empty lines you see.

I am working on fixing this issue. Thanks. :)

**Comment by DeathTech154** [comment]
This issue should be fixed for the next hotfix.
The hotfix should be getting released today.

Thanks for reporting this issue.
